
#include "counterparty_utils.h"

static const uint8_t AMOUNT_MAX_SIZE = 22;

static const unsigned char PREFIX_START = 0;
static const unsigned char PREFIX_LENGTH = 8;

static const unsigned char MESSAGE_START = 8;
static const unsigned char MESSAGE_LENGTH = 1;

static const unsigned char GIVE_ASSET_START_ORDER = 9;
static const unsigned char GET_ASSET_START_ORDER = 25;

static const unsigned char ASSET_START_ENHANCED_SEND = 9;
static const unsigned char ASSET_LENGTH = 8;

static const unsigned char AMOUNT_START_ENHANCED_SEND = 17;
static const unsigned char AMOUNT_LENGTH = 8;


static const unsigned char GIVE_AMOUNT_START_ORDER = 17;
static const unsigned char GET_AMOUNT_START_ORDER = 33;


static const unsigned char ADDRESS_START_ENHANCED_SEND = 26;
static const unsigned char ADDRESS_LENGTH = 20;


const char * const  divisibleTokens[] = { "BAAA","BABCOIN","BADACOIN","BADASS","BAKUHATU","BALUS","BANANACOINS","BANDCOIN","BANDONEON","BANKCOIN","BANZAI","BARROWBITS","BASICINCOME","BASILCOINS","BASTARDCOIN","BCGREEN","BCOUNTERFEIT","BCRYPTO","BDCOIN","BEACONLAW","BEARD","BEBECOIN","BEEP","BELGIAN","BERNIECOIN","BESTPRICE","BFIS","BIENCOIN","BIGBOOBS","BIGGUY","BILLIARDCOIN","BILN","BIRTHDAYGIFT","BITAMERICA","BITBLTCOIN","BITCAFECOIN","BITCOINCASH","BITCOINCHAN","BITCOINCHECKER","BITCOINEX","BITCOINJESUS","BITCOINTOKEN","BITCRYSTALS","BITETHER","BITGIL","BITGIRLSI","BITGIRLSII","BITLAUREL","BITMONETA","BITSHARE","BITSHIELD","BITSHIELDFS","BITSIES","BITSPA","BITSTICK","BITSUPRA","BITTICKER","BKGOLDCOIN","BKJCOIN","BLACKHAND","BLACKKIGYOU","BLCEDUCATION","BLEMFLARKS","BLESSINGS","BLINGZ","BLINK","BLINKZ","BLOCKFINANCE","BLOCKLABEL","BLOT","BLUECHIPS","BLUMES","BOBC","BOJCOIN","BONANNO","BOOKKEEPER","BORIKOIN","BOXXCOIN","BPEPGENERAL","BPMBIT","BPTS","BRANDON","BRAZUCA","BRBN","BRITISHPOUND","BROADBEANS","BRONERO","BTCBLUE","BTSM","BTSY","BTSYTEST","BTWAY","BUBBLES","BUDZ","BULLETPOINTS","BUNDESMARK","BURGERLOVER","BURICOIN","BXSX","BZCOIN","CACASSET","CACC","CACCOIN","CACCTIP","CAKB","CANNABISCLUB","CANNABITSEED","CANTOKEN","CAPCOIN","CATALUNYA","CATTLEBOND","CAYKO","CCCOIN","CCFUND","CCFUNDAA","CCFUNDST","CCINDEXFAA","CCOIN","CFBTC","CFCTOKEN","CHAMPAGNE","CHARITYCOIN","CHARMDUST","CHICKENMAN","CHIKARIN","CHIKARINVIX","CHIKUWA","CHILOE","CHIPS","CHKNDP","CHORALE","CHRISTCOINS","CHULAVISTA","CHURCHCOINS","CICACOIN","CICC","CIGARCASH","CIGARCOIN","CINECOINS","CIRCUITREE","CKCCOIN","CLASHOFCLAN","CLDCOIN","CLEFCARD","CLOUDMINING","CLOVERMONEY","CNPCARD","CNPCOIN","CNYMINT","COCOCASH","COCOJP","CODELOGICMONEY","COFFEEBTC","COFFEECUP","COFFEESCOIN","COHARUTA","COINDADDY","COINPORTAL","COINREPUBLIC","COINSTOP","COINVEND","COINWHALE","COLLA","COLLIDERCOIN","COLOMBO","COMICFOUNDER","COMICVOTEONE","COMITCOIN","COMMCONTROL","COMMODORE","COMSA","CONGRATS","CONTRABAND","COOPETITION","COREFIVE","COSMICPEPE","COUNTCHOCULA","COVALC","COVALTEST","CPFTEST","CPFVOTE","CPIF","CPMUSIC","CPNEWS","CRIMECOIN","CROPS","CROWDCOIN","CRYPTOBUILD","CRYPTOCENTER","CRYPTOCLUB","CRYPTOCOINS","CRYPTOFUN","CRYPTOGENE","CRYPTOHIVE","CRYPTOMACHINES","CRYPTONN","CRYPTOTARIAN","CTGTOKEN","CYBERSHARES","CYUNNUBO","DACHIN","DAIFUKU","DAIGO","DAISHIN","DAMGENETICS","DANIELPBARRON","DAOKA","DAOPEPEHACK","DARIOCOIN","DARKCLAM","DARKDONALD","DATABITS","DAVACOIN","DAVIDDOLLAR","DAVIDRALLEN","DEBITCOIN","DECOIN","DELPHIS","DEMODAY","DEMOSCENE","DENBE","DENNOU","DEVMED","DEVPARTY","DEXCOIN","DHARMA","DIGINSIDE","DIGITAL","DIGITALWOW","DIRT","DIVECOIN","DIVIDENDPLUS","DJASANYAN","DJASANYANVIX","DJJSCRILLA","DNTD","DOBERBIRD","DOGA","DOGBIT","DOGECREDITS","DOGERO","DOGEZA","DOGRESCUE","DOHOD","DOMAINPLUS","DORAGONBALL","DOUBLEHASH","DOUGH","DRAGHI","DRAGONBALLSZ","DRAGONTIX","DRAGONZAPP","DROPLORDCOIN","DTCOIN","DUBAIPOINTS","DURANDAL","DUSTCOIN","DUTCHHAMMER","EAMONNW","EARNFREEBTC","EARTHCASH","EBITS","ECFXSVC","ECOSTOCK","EDGFDS","EDSCONTRIB","EEGN","EEHEE","EGOLI","EKWANZA","EMERSONIAN","EMOJIPEPE","EMXBIT","ENER","ENKOUGIRL","EPAYCOIN","EPESO","ERICCOIN","ERMUUN","ESCOIN","ESCX","ESECOIN","ESTORE","ESUNBANK","ETHEREUMCARD","EUCS","EUROPIAN","EUROVISION","EVANGELION","EVOO","EXDEMO","EXOTICDUBIA","EXPT","EXTHB","EXTOKEN","FANTOKEN","FAUCETPEPE","FDCARD","FDSBIT","FEEDMESPORTS","FEELINGS","FINLAND","FIRSTVOTEWS","FIVEOFIVE","FLASCOIN","FLDC","FLDCTEST","FLDCVOTEI","FLDCVOTEII","FLDCVOTEIII","FLINTSTONE","FLOWCASHUSD","FLOWERCOIN","FLOWERCOINS","FORMICACOIN","FOURS","FOXWFC","FREEROSS","FRIGG","FSCC","FUCHINASHI","FUCKHANLIN","FUCKTRUMP","FUCTUM","FUKUKICHI","FUKUOKACOIN","FUNBUCKS","FUNDTWO","FUSAN","FUTCOIN","FUTURECREDIT","FXOPENCRYPTO","GACHA","GAKKO","GAKKY","GALGO","GAMBARE","GAMBINO","GANOTEST","GAPC","GASCOINS","GASTROHEALTH","GAVAS","GAVYNCOIN","GAZCOIN","GBPX","GCGBM","GCMC","GCOIN","GEMBISCOIN","GEMZ","GEMZCARD","GENCOIN","GENESISCARD","GENOVESE","GENSEN","GENTCOIN","GETBITS","GHANACASH","GIFHUB","GIGAHASH","GIGTOKEN","GISI","GITC","GIVABITCOIN","GODTANU","GOGOBIT","GOLDENMOOSE","GOLDKEY","GOLDTICKET","GOOBER","GOODMORNING","GOOON","GORILLAGLUE","GORILLAZ","GOTTSUCOIN","GOUMOU","GOZARU","GPCOIN","GPCOINSEC","GPSCOIN","GPTCOIN","GRAHAMLIMIT","GRANDCOIN","GREEKCOIN","GRIDTOKEN","GTXC","GUERILLA","GUEVARA","GUMMA","HABESHA","HACKLABEURO","HAFVEN","HAGE","HAGEZENI","HAKATAGOLD","HAKUTAKA","HANSEI","HAPPYEGG","HAPPYNEWYEAR","HARAMBUX","HARUHARU","HATENA","HAYSTACK","HELSINKI","HERB","HERBSTEPHENS","HESOKURI","HIGUCHI","HIKARUAMAMI","HIKOUSEKI","HINANOMAI","HIROT","HITODEMAN","HLTH","HOKUDAI","HOLDIT","HOLIDAYCOIN","HOLONSWARM","HOMALLICOIN","HOMMALICOIN","HONMARU","HONWK","HOPECOIN","HORIEMONCARD","HORUSCOIN","HOTELJUNKIES","HOUSECOIN","HQLEADERS","HUMANCOIN","HYBRID","HYOGO","HYOU","HYPERBALL","HYUGA","IAMCOIN","ICARUS","ICHARLOTTE","ICHIRO","ICOBANK","ICOCA","ICOIN","ICQCOIN","IDEOANGELS","IDEOFOUNDER","IDISNEY","IFCOIN","IFIT","IFNM","IMAICOIN","IMBC","IMCA","INAGOCASH","INDIESQUARE","INFCOIN","ININCHAN","INSTCOIN","IRCCOIN","IREX","IRONCLADWEB","ISLAMAPTOKEN","JACKSONCOIN","JACOIN","JANOM","JAPANBANK","JAPANICOIN","JAPANMENSA","JAPARIGOLD","JAPCOIN","JAROKNCOIN","JBPCOIN","JDIS","JENGA","JEROMEBAKER","JERRYGARCIA","JESUS","JGBCOIN","JHANNAHCOIN","JIMCOIN","JIMINTO","JINGO","JINROUSAKABA","JIRU","JLCOIN","JMADE","JONACOIN","JORDANROOKIE","JOSHTOKEN","JPBEAR","JPBULL","JPYTEST","JSTAMP","JUBILEECOIN","JUDOBI","JUNCOIN","KAERUMARIO","KAGE","KAIKETSUZGLD","KAIYACOIN","KAKIECOIN","KAKIP","KALLEO","KAMAKARA","KAMIDANOMI","KAMON","KAMPA","KANNA","KAORI","KARASAWA","KARINCOIN","KARMATOKEN","KASOU","KATCHANCOIN","KATIOCOIN","KAWAII","KAWASAKIZ","KBTIT","KEEPTHEFAITH","KEKCOIN","KEMURI","KENBI","KENCOIN","KEVCOIN","KIKOUSHI","KIME","KINC","KINDRTEST","KINGBOMBIE","KINGSLAMMA","KINMEDAL","KINOARIGATO","KINOKOUSAKA","KIRISHIMA","KITACA","KITAKAMICOIN","KITCHENBOWL","KIWA","KIZUNA","KIZUNADIA","KIZUNAGOLD","KJPY","KLST","KMAKECHI","KMAMAGO","KMARIMA","KMASAI","KMASAKURA","KMASHIKAGA","KMCHOSOKABE","KMFUKUSHIMA","KMGAMO","KMHACHISUKA","KMHONDA","KMHOSOKAWA","KMII","KMIMAGAWA","KMISHIDA","KMKATAKURA","KMMATSUNAGA","KMMOGAMI","KMNAOE","KMOTOMO","KMSANADA","KMTAKENAKA","KMTODO","KMTOKUGAWA","KMYAGYU","KOINIFY","KOKADUKATS","KOLMANCOIN","KOMA","KOMOCOIN","KOSMOSKREDIT","KOTOBUKI","KOUDAI","KOYAMACOIN","KOZO","KRISH","KSHARES","KSTOKEN","KTEST","KUBOCOIN","KUMAMONCARD","KUMAPR","KURODA","KUSA","KWDCOIN","KYJCOIN","LAICHU","LAKH","LAMEN","LASTCRYPTO","LAURACOIN","LEAFCOIN","LECHAT","LENTERACOIN","LETOUR","LETSTOKEN","LEXIUM","LGTPRE","LICIN","LILL","LINDENDOLLAR","LIRA","LLCSRC","LOANCOIN","LOCALCOIN","LOCX","LOISTOCOIN","LORDKEK","LOTTOKING","LOVECOIN","LOVEHEART","LOVENEST","LOYALTYCARDS","LSKYWALKERCD","LTBCOIN","LTBNETWORK","LUCCHESE","LUMIERE","LUNE","MACROSS","MADARA","MADOKACOIN","MAFALPHA","MAFCOIN","MAGEZENI","MAGICAR","MAGICFLDC","MAHO","MAIDSAFE","MAIKO","MAIMAI","MAKIT","MALAKAS","MAMASCHICKEN","MAMECOIN","MAMEMAKI","MAMICHANNEL","MANAGEDFUNDS","MANEKINEKO","MANEPACARD","MANJI","MANNASWARM","MAPPYCARD","MARBLES","MARGINRIGHT","MARIHUANA","MARIN","MARIOS","MARSBOND","MARUZEI","MARUZEMI","MASAMI","MASASHI","MASSPSYCH","MATADORPEPE","MATC","MATSUIKENJI","MATSUMOTOKEN","MATSURICOIN","MATSUSAKAGYU","MAXICOIN","MBITCOIN","MCAP","MDRFT","MEDICALHERO","MEDICISTOCK","MEGAFLASH","MENTHO","MEPCOIN","MERONCHAN","MESHICOIN","METAINTEREST","METALCOIN","METAXCP","MFIT","MGMC","MICOOEYCOIN","MIHOBOO","MIJINCOIN","MIKECAT","MIKKELLER","MILESANDMORE","MILKMONEY","MINANDOANDO","MINARIN","MINERALS","MINERCOIN","MINERGARAGE","MINERPAY","MINERSCOIN","MINEUCHI","MINTCNY","MINTO","MIPRO","MIRACLEKUMA","MIRUCOIN","MIRUSHIRU","MISACOIN","MITRCOIN","MITSUICOIN","MITSUKOSHICO","MITSUSANCOIN","MIZUKI","MIZUKIVIX","MLEONPRO","MOAS","MOBICOIN","MOBILIZED","MOECOIN","MOGAMIN","MOJI","MOMOSUKECOIN","MONACHO","MONACOIN","MONADAISUKE","MONAMIN","MONAMINCOIN","MONAPARTY","MONEROJ","MONKEYBUCKS","MONSTERBALL","MOOLAH","MOONBIT","MOORCOIN","MOPHANTHA","MOSYN","MOUKOTANMEN","MOULDY","MPBTC","MPTSTOCK","MRCAM","MRCBKK","MRCDEMO","MRFLAWLESS","MSBITCOIN","MSBLOCKCHAIN","MSTC","MTCOIN","MTMALBUM","MTMSONG","MUGEN","MUKE","MURICA","MXJXN","MYDARTS","MYFRIENDS","MYPOINTS","MZOU","NAGESENCH","NAGEZENI","NAGEZENII","NAGEZENY","NAIRANOTE","NAIRAPLUS","NAJBEZ","NAJCOIN","NAKANOAZUSA","NAKASUCOIN","NAKATOCOIN","NANOPARTICLE","NANZAN","NAPPA","NASDAQAPPLE","NASUBI","NBCOACHING","NCXC","NECTARIUM","NEEDEDTHINGS","NEEDMONEY","NEKO","NEMBER","NEMCOIN","NERV","NETJET","NETX","NEUREAL","NEWMUSIC","NGXX","NHZDOGE","NHZZENHASH","NICOIN","NIGHTCOIN","NIHOMBASHI","NIKUKAI","NINJASHARE","NIPOPIN","NIPPONCOIN","NISHIKAWA","NITOBE","NIXX","NLTR","NMANI","NNTOKEN","NOGUCHI","NOKCOIN","NONECOINSK","NOSMOKE","NOUMI","NOVATOKEN","NOWAR","NPOINT","NSRV","NUDEPEPE","NUGGZ","NULLPO","NUMA","NUMAZU","NUREUS","NVOT","NVST","NXHD","NYAA","NYAAANCOIN","NYAMOSAN","NYAN","NYANCO","OAZT","OBIHIRO","OBITER","OCHINCOIN","OCTO","OFAC","OFFPACOIN","OGWCOIN","OHAJIKI","OHINERITIP","OHYB","OICOIN","OILCOINS","OKADACOIN","OKIC","OKINAWARAIL","OKINI","OKUCOIN","OKUYEN","OMAK","OMAKECOIN","OMOCHICOIN","ONESATOSHI","ONETHOUSAND","ONIGIRI","ONIONBOY","ONIYOME","OOKAMI","OPCU","OPENOPALS","OPHION","OPTICTOPIC","OPTUSCOIN","ORIG","OSCC","OSSAN","OSUSHI","OTAFUKU","OTCHOUSE","OTOCOIN","OTONA","PACHI","PANDAGOLD","PANICFAT","PAULCOIN","PBMBIT","PEANUTS","PEERPAY","PEGTOKEN","PENIS","PENISIUM","PEPEBAGGINS","PEPEBUCKS","PEPECASH","PEPECASHGOLD","PEPEGUN","PEPEKUDOS","PEPENATION","PEPEPASSPORT","PEPERIGHTLEG","PEPETOKEN","PEPETRATION","PERICAN","PERKPOINT","PETAMINE","PEYOTE","PFCOIN","PHELPSFACE","PIAN","PICACHU","PICCOLO","PICKUPBALL","PIECEOFEIGHT","PIKACYU","PINECOIN","PINKPOM","PIXULECO","PLATONCOIN","PLAZACOIN","PLIPCOIN","PODCAST","POKEMON","POOLCOIN","PORNCASH","POTIONS","POUNTERCARTY","POWC","POWR","PPFS","PRATTBITS","PRESCOIN","PROG","PROMCOIN","PROSPERITY","PROTONEXIUM","PROTONEXUM","PROTOONE","PSYCOIN","PUBPHONE","PUCHICOIN","PUKKA","PUNTIPCDR","PUSSY","PUTIP","PWRUPKINOKO","QRYPTO","RAAMEN","RAPIDGROWTH","RAREPEPECOIN","RAREPEPEFONZ","RATECOIN","RCTICKET","REAKTOR","REALDEALIUM","REDPC","REIT","RENKIN","REPUBLICOIN","RESORTLIFE","RETICECOIN","REVINACOIN","REVIT","RIKIO","RIPPLECARD","RIPPLES","RISAVIX","RISONA","RISOSESU","RKGKCOIN","ROCKD","ROGERPOWWER","ROKUMONSEN","ROMANTOKEN","ROMCOIN","ROOMBCC","ROOTCOIN","ROVIO","RPDF","RRAMMINI","RRCOIN","RTCOIN","RUMIRUMI","RUNACOIN","RURU","RUSTBITS","RUUCOIN","RYOU","SAGI","SAITOH","SAKURACOIN","SAKURAKOIN","SALARYCOIN","SAMGYEOPSAL","SAMOURAI","SANOMAYA","SANOMAYAVIX","SANSEI","SAPO","SARU","SARUTOBI","SARUTOBICARD","SATCOIN","SATOAYAKA","SATONAKA","SATOSHICARD","SAUNA","SAURUS","SBCOIN","SBITCOIN","SCAMMIES","SCHOOLCOIN","SCJX","SCOTCOIN","SCOTTCOIN","SCUDOCOIN","SDST","SEDOLCOIN","SEKHMET","SEKIHEKI","SEMICOIN","SETAGAYA","SEXCASH","SEXYHONEY","SHADHANA","SHAKEEN","SHAPESHIFTCD","SHAPIRA","SHICOIN","SHIHPIN","SHIMAON","SHIMARENA","SHIRAHOSHI","SHIROKKI","SHISHINN","SHIT","SHREDITS","SHUMAI","SICC","SIGURE","SILVERBITS","SIMO","SIMONSCOIN","SINGULARITYI","SIRAHOSIVIX","SISTERCITIES","SJCT","SJCX","SKULLCOIN","SKYLINEGTR","SKYTOKEN","SLOVAKCOIN","SMALLBIT","SMILEBIT","SMOKETOKEN","SMSBITCOIN","SOBITCOIN","SOGACOIN","SOLOMONCOIN","SONCOIN","SORY","SOUP","SOUTHER","SOVCOIN","SOVEREIGNC","SPAMCOIN","SPECULATE","SPERM","SPLATOON","SPLOTCOIN","SPONSOR","SPORTARBS","SPTC","SPTCTEST","SPTOYTOKENA","SRTCOIN","SSPCOIN","SSTC","STAPPID","STARWARSCARD","STBV","STEEMSTARS","STLCOIN","STORMWIND","STUFFCOIN","SUBLIMINAL","SUMI","SUPCOIN","SUPERCELL","SUUCOIN","SWARM","SWARMCD","SWARMOPSNPO","SWARMPRE","SWARMVOTETWO","SWARO","SWATO","SWMCHEX","SXBETA","SYLPHID","SYMBIT","SYOBON","SYRIZA","TABITA","TABLETENNIS","TAGK","TAHI","TAHIBONUS","TAIPEIBTC","TAISHO","TAKAKKARD","TAKARA","TAKASE","TAKECASH","TAKEMON","TAKEOCARD","TALANT","TAMPON","TAMUKEN","TANITA","TANOMOSI","TASCAL","TASX","TATIANACOIN","TATIANAFAN","TATSUYA","TAVELCOIN","TAWAWA","TAXICOIN","TBMC","TEGENAN","TELSTRACOIN","TEMPC","TEQUILA","TERMTEM","TESTASACOIN","TESTCOIN","TESTCOINS","TESTGOLDMINE","TESTICOINS","TESTKTEST","TESTNETPEPE","TETLAS","TFXC","THBS","THEACOMPANY","THEDAFT","THEPLAYA","THETIMESCARD","THOUGHTCOIN","THRIFTCARD","THRIFTCOUPON","TIEAMEX","TILECOINX","TIMEPIECE","TINCOIN","TINDER","TITHECOIN","TKDCOIN","TOBISACOIN","TOBIT","TOKENLY","TOKENZ","TOKNS","TOKYOFAFA","TOMIO","TOMOCOIN","TOMOYA","TONAKAI","TONKOTSU","TOPCOIN","TOREKABUOPT","TPCTEST","TRADINGCOACH","TRANCEFAMILY","TRASHCOIN","TREPCOIN","TRHC","TRICKORTREAT","TRIGGERS","TROPTIONS","TRUFFLETOKEN","TRUTHGROUP","TSUCHIDA","TSUKASA","TSUKASAVIX","TURIBITCOIN","TUTORIAL","TWBTC","TWOLIVEPEPE","UDON","UGTOP","UIPCOIN","UKERU","ULTMTTOKEN","ULTRARICH","UMEBOSHICOIN","UMECOIN","UMETANCOIN","UMOK","UNIT","UNIVERSECOIN","UNLUCKYPEPE","URAWAZAKUN","URCOIN","USCTROJANS","USDMINT","UZUKI","VAGINA","VAIROCANA","VALYOU","VAPORSWARM","VAYERN","VEIKKAUS","VFAUCET","VIPPER","VISIONCOIN","VIVICOIN","VNDL","VOTCHICOIN","VRGC","VRYEN","VYKTORYDOLLAR","WABISABI","WAKKA","WALMART","WANK","WARAI","WARASHIBE","WATTS","WAYNECHAIN","WDBCOIN","WEEDBITS","WFBD","WFWD","WHCOIN","WHORE","WILLCOIN","WINPASS","WOODENNICKEL","WOODSHARES","WORLDCASH","WORLDPEACE","WORTHLESS","WRCC","WRITERSCOIN","WSTCOIN","WTBNAME","XABERDEENFC","XALOHABIT","XAPCOIN","XAQA","XARB","XARGO","XATG","XBNC","XBNT","XBNX","XBTC","XCELTIC","XCOM","XCP","XCPRETURNPLZ","XDAY","XDJOKOVIC","XEERCOIN","XFCCOIN","XFER","XFOCUS","XFOWLER","XFOX","XFUD","XGEM","XGMTEST","XHEARTS","XHYK","XIEXIE","XISNER","XJOHNSON","XKILMARNOCK","XKUMA","XMOTHERWELL","XMURRAY","XNEWCASTLE","XNRG","XOPOWO","XOTIKATV","XPARTICK","XPLDNBTC","XPLDNBTCCRD","XQNPOSFUND","XQNTOKEN","XRAHM","XRANGERS","XRAONIC","XREP","XROSSCOUNTY","XSMILE","XSTAR","XSTENSON","XTHIEM","XTHOMAS","XTROPTIONS","XVANGERWEN","XWAWRINKA","XXANDOCOINXX","YAAMAEMON","YACHTMONEY","YAGI","YAJUCOIN","YAMADACOIN","YAMAGUCHIA","YAMASE","YAMETAI","YAPCOIN","YEABABY","YELLEN","YKCOIN","YOGOTOKEN","YOME","YOTACOIN","YRASHK","YUKICHI","YUMECOIN","YUTACOIN","YUTTYCOIN","YUYUYUCOIN","ZABETH","ZADAO","ZAIF","ZAPPA","ZARRA","ZBBB","ZDNX","ZEON","ZHXM","ZOHAR","ZONACOIN","ZONO","ZTRUST","ZUIZUI",0};

 bool checkDivisible(char *token){
 
 int i = 0;
 while(PIC(divisibleTokens[i])){
    if(PIC(strcmp(PIC(divisibleTokens[i]),token)) == 0){
       
        return true;
    }
    i++;
 }
  
     return false;
  
   
}



uint64_t
convertToDecimal (unsigned char *array, unsigned char n)
{
  uint64_t result = 0;

  while (n--)
    {
      result <<= 8;
      result += *array;
      array++;
    }
  return result;
}


//stolen from stellar app
unsigned short
print_long (uint64_t id, char *out)
{
  char buffer[AMOUNT_MAX_SIZE];
  uint64_t dVal = id;
  int i, j;

  memset (buffer, 0, AMOUNT_MAX_SIZE);
  for (i = 0; dVal > 0; i++)
    {
      buffer[i] = (dVal % 10) + '0';
      dVal /= 10;
      if (i >= AMOUNT_MAX_SIZE)
    {
      THROW (0x6700);
    }
    }
  // reverse order
  for (i -= 1, j = 0; i >= 0 && j < AMOUNT_MAX_SIZE - 1; i--, j++)
    {
      out[j] = buffer[i];
    }
  out[j] = '\0';
  return j;
}



void decodeAssetID (uint64_t assetID, unsigned char*out)
{
       //counterparty assetid to assetname function

      char b26_digits[] = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";

      unsigned char rem = 0;

      uint64_t div = 0;

      char asset_name_tmp[21];

      unsigned char nameLength = 0;

      while (assetID > 0)
    {

      div = assetID / 26;

      rem = assetID % 26;

      assetID = div;

      asset_name_tmp[nameLength] = b26_digits[rem];

      nameLength++;
    }

      //name is backwards so we need to reverse it

      for (unsigned char i = 0; i < nameLength; i++)
    {

      out[nameLength - (i + 1)] = asset_name_tmp[i];

    }

      //add string limiting null character
      out[nameLength] = '\0';
}




int
unpack (unsigned char key[], unsigned char keySize, unsigned char data[],
    unsigned char dataSize, unsigned char *fullAmount,
    unsigned char *tokenName, unsigned char *cpHash160, unsigned char *getAsset, unsigned char *giveAsset, unsigned char *getAmount, unsigned char *giveAmount)
{


  //arc4 decrypt the data
  unsigned char S[256];

  for (int i = 0; i < 256; i++)
    {

      S[i] = i;

    }


  for (int i = 0, j = 0; i < 256; i++)
    {

      j = (j + S[i] + key[i % keySize]) % 256;

      int tmp1 = S[i];
      int tmp2 = S[j];
      S[i] = tmp2;
      S[j] = tmp1;

    }

  unsigned char ret[dataSize];


  for (int x = 0, i = 0, j = 0; x < dataSize; x++)
    {

      i = (i + 1) % 256;

      j = (j + S[i]) % 256;

      int tmp1 = S[i];
      int tmp2 = S[j];
      S[i] = tmp2;
      S[j] = tmp1;

      int K = S[(S[i] + S[j]) % 256];

      ret[x] = (data[x] ^ K);

    }

  int messageType = ret[MESSAGE_START];

  if (messageType == TYPE_ORDER)
    {


      unsigned char getAssetData[8];

      os_memmove (getAssetData, ret + GET_ASSET_START_ORDER, ASSET_LENGTH);

      //convert numeric hex string into long well uint64_t because ledger dont like longs
      uint64_t getAssetId = convertToDecimal (getAssetData, 8);

      decodeAssetID(getAssetId,getAsset);


      unsigned char giveAssetData[8];

      os_memmove (giveAssetData, ret + GIVE_ASSET_START_ORDER, ASSET_LENGTH);

      //convert numeric hex string into long well uint64_t because ledger dont like longs
      uint64_t giveAssetId = convertToDecimal (giveAssetData, 8);

      decodeAssetID(giveAssetId,giveAsset);




      //parse amount data from decrypted data
      unsigned char get_amount[8];
      
      os_memmove (get_amount, ret + GET_AMOUNT_START_ORDER, AMOUNT_LENGTH);

       if(!checkDivisible(getAsset)){ 

         uint64_t getAmountLong = convertToDecimal (get_amount, 8);

        //convert long to string as ledger cant use snprintf with uint64_t
         print_long (getAmountLong, getAmount);

        }
        else {

          btchip_context_D.tmp = (unsigned char *) (getAmount);//TODO is this needed?

            unsigned short textSize = btchip_convert_hex_amount_to_displayable (get_amount);

           getAmount[textSize] = '\0';

      }



      




       //parse amount data from decrypted data
      unsigned char give_amount[8];
      
      os_memmove (give_amount, ret + GIVE_AMOUNT_START_ORDER, AMOUNT_LENGTH);

     if(!checkDivisible(giveAsset)){ 

         uint64_t giveAmountLong = convertToDecimal (give_amount, 8);

        //convert long to string as ledger cant use snprintf with uint64_t
        print_long (giveAmountLong, giveAmount);
      }
      else {

          btchip_context_D.tmp = (unsigned char *) (giveAmount); 

            unsigned short textSize = btchip_convert_hex_amount_to_displayable (give_amount);

           giveAmount[textSize] = '\0';

      }


     


    }
  else if (messageType == TYPE_ENHANCED_SEND)
    {


      

      os_memmove (cpHash160, ret + ADDRESS_START_ENHANCED_SEND, ADDRESS_LENGTH);


      //parse amount data from decrypted data
      unsigned char amount[8];
      
      os_memmove (amount, ret + AMOUNT_START_ENHANCED_SEND, AMOUNT_LENGTH);
 



      unsigned char assetData[8];

      os_memmove (assetData, ret + ASSET_START_ENHANCED_SEND, ASSET_LENGTH);

      //convert numeric hex string into long well uint64_t because ledger dont like longs
      uint64_t assetid = convertToDecimal (assetData, 8);

      decodeAssetID(assetid,tokenName);
 


        if(!checkDivisible(tokenName)){ 

            uint64_t amountLong = convertToDecimal (amount, 8);


            //convert long to string as ledger cant use snprintf with uint64_t
             print_long (amountLong, fullAmount);



        }
        else
        {

            //token is divisible so pass to ledger btc amount formater function to divide numeric hex string by 10^8 and convert to displayable string

            btchip_context_D.tmp = (unsigned char *) (fullAmount);

            unsigned short textSize = btchip_convert_hex_amount_to_displayable (amount);

            fullAmount[textSize] = '\0';


            //if the user wants to send 1 INDIVISIBLETOKEN a hacker could change the transaction before it hits the ledger to 
            //send 100000000 INDIVISBLETOKEN and set the flag as divisible meaning the ledger app would show 1* the aterix should 
            //warn the user that the real amount has been dvided for display puposes which is strange as this is not the case for in divisible tokens 


    }

    }else if(messageType == TYPE_CANCEL){
        //do nothing
    }

  return messageType;

};
